name: Run tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        x:
          - gemfile: 'rails_4.2'
            ruby: '2.3.8'
          - gemfile: 'rails_5.0'
            ruby: '2.4.7'
          - gemfile: 'rails_5.1'
            ruby: '2.4.7'
          - gemfile: 'rails_5.2'
            ruby: '2.4.7'
          - gemfile: 'rails_5.0'
            ruby: '2.5.6'
          - gemfile: 'rails_5.1'
            ruby: '2.5.6'
          - gemfile: 'rails_5.2'
            ruby: '2.5.6'
          - gemfile: 'rails_5.2'
            ruby: '2.6.3'
          - gemfile: 'rails_5.2'
            ruby: '2.7.4'
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.x.gemfile }}.gemfile
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.x.ruby }}
          bundler-cache: true
          cache-version: 2
      - run: bundle exec appraisal ${{ matrix.x.gemfile }} rake test
